#!/bin/bash
echo "=========================================="
echo "    Yak Live Failover Demo Instructions   "
echo "=========================================="
echo ""
echo "This demo is meant to be run manually across 4 terminals."
echo "Please read the full instructions in: scripts/README_DEMO.md"
echo ""
echo "Quick Reference Commands:"
echo "-------------------------"
echo "Terminal A (Leader):"
echo "  REDIS_HOST=localhost BROKER_ID=broker-1 ROLE=leader HOST=127.0.0.1 PORT=8001 PEER_URL=http://127.0.0.1:8002 uvicorn broker.app:app --port 8001"
echo ""
echo "Terminal B (Follower):"
echo "  REDIS_HOST=localhost BROKER_ID=broker-2 ROLE=follower HOST=127.0.0.1 PORT=8002 PEER_URL=http://127.0.0.1:8001 uvicorn broker.app:app --port 8002"
echo ""
echo "Terminal C (Producer):"
echo "  python -m producer.producer_cli batch --count 40 --delay 0.5"
echo ""
echo "Terminal D (Consumer):"
echo "  python -m consumer.consumer_cli follow --interval 1.0"
echo ""
